# Generated by Django 2.2 on 2021-02-11 02:38

from django.db import migrations, models
import django.utils.timezone
import harbor_international_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('harbor_international_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=3000)),
                ('video', models.FileField(upload_to='video/%y', validators=[harbor_international_app.validators.file_size])),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='caption',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
