# Generated by Django 2.2 on 2021-02-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbor_international_app', '0002_auto_20210210_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='video/', verbose_name=''),
        ),
    ]
