# Generated by Django 2.2 on 2021-03-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbor_international_app', '0005_auto_20210217_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algebra',
            name='content',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
