# Generated by Django 2.2 on 2021-01-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_remove_registration_birthday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='User',
        ),
    ]
